#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import os
import re
import subprocess as sp
import sys
import textwrap
import time
from enum import Enum, IntEnum
from typing import NamedTuple

import requests
import yaml
from requests import codes
from requests.packages.urllib3.exceptions import InsecureRequestWarning

try:
    import xml.etree.cElementTree as eTree
except ImportError:
    import xml.etree.ElementTree as eTree

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)


COMPONENTS = ["cluster_manager", "oz_panel", "oz_worker"]

LOGS = [
    ("[oz_panel]", "/var/log/oz_panel"),
    ("[cluster_manager]", "/var/log/cluster_manager"),
    ("[oz_worker]", "/var/log/oz_worker"),
]
LOG_LEVELS = ["debug", "info", "error"]

# If onepanel is started from sources, contains the path to the root directory
# of the pre-built onepanel repo/artifact.
ONEPANEL_OVERRIDE = "ONEPANEL_OVERRIDE"

# Username to be used in Basic auth with the emergency passphrase
PASSPHRASE_USERNAME = "onepanel"
EMERGENCY_PASSPHRASE_VARIABLE = "ONEPANEL_EMERGENCY_PASSPHRASE"

LEGACY_VM_ARGS_SOURCES_PATH_TEMPLATE = "_build/default/rel/{component}/etc/vm.args"

ONP_GENERATED_CONFIG_SOURCES_PATH = (
    "_build/default/rel/oz_panel/etc/autogenerated.config"
)
ONP_VM_ARGS_SOURCES_PATH = "_build/default/rel/oz_panel/etc/autogenerated.vm.args"

LEGACY_VM_ARGS_PACKAGES_PATH_TEMPLATE = "/etc/{component}/vm.args"

ONP_GENERATED_CONFIG_PACKAGES_PATH = "/etc/oz_panel/autogenerated.config"
ONP_VM_ARGS_PACKAGES_PATH = "/etc/oz_panel/autogenerated.vm.args"

AUTOGENERATED_VM_ARGS_TEMPLATE = """# MACHINE GENERATED FILE. DO NOT MODIFY.

## Name of the node
-name {node}

## Cookie for distributed erlang
-setcookie {cookie}
"""

MSG_COULD_NOT_RESOLVE_VERSION = """Could not resolve the previously deployed software version;
for versions < 25.1, this information is not supported. Assuming the previously running
version was NOT LOWER THAN 20.02.1.

WARNING: if you are upgrading from version 19.02.* or lower, STOP the deployment
and first upgrade to 20.02.*. Otherwise, let it continue.

Sleeping for 30 seconds to let you react...
"""

SLEEP_COULD_NOT_RESOLVE_VERSION_SEC = 30

MSG_FRESH_DEPLOYMENT = """No previous persistence detected.

This is a fresh deployment of Onezone in version {new_version}
"""

MSG_RESUME_SAME_VERSION = """Preexisting persistence has been detected, version {prev_version}

Resuming Onezone in version {current_version} ...
"""

MSG_RESUME_UPGRADE = """Preexisting persistence has been detected, version {prev_version}

Resuming Onezone in version {current_version} - an upgrade will be performed
during the startup of services. Please allow more time until the services are operational.

You may monitor the logs for details (paths inside the container):
/var/log/oz_panel/info.log
/var/log/oz_worker/info.log
"""

MSG_UPGRADE_JUMP_TOO_BIG = """Preexisting persistence has been detected, version {prev_version}

ERROR: You are attempting to run Onezone in version {current_version}
Upgrading by more than one major versions is not supported. Please upgrade to
an intermediate major version first, then start this version. Note that majors
21 and 25 are treated as the same one, due to reworked naming convention.

Exemplary allowed upgrades:
    21.02.8 -> 25.0
    21.02.2 -> 26.0
    25.0 -> 25.1
    25.1 -> 26.1
    20.02.6 -> 25.1

Exemplary disallowed upgrades:
    20.02.20 -> 26.0  (upgrade to 21.02.* / 25.* first)
"""

MSG_DOWNGRADE = """Preexisting persistence has been detected, version {prev_version}

ERROR: You are attempting to run Onezone in version {current_version}
Downgrades are not supported. Please use Onezone in version {prev_version}
or newer.
"""

WRAP_KWARGS = {"width": 100, "break_long_words": False, "break_on_hyphens": False}

SERVICE_READY_LOCK_FILE = "/root/service-ready.lock"  # used by the "await" script

MSG_CONGRATULATIONS = "\nCongratulations! New Onezone deployment successfully started."
MSG_WAITING_FOR_CLUSTER = "\nWaiting for existing cluster to start..."
MSG_RESUMED_WORK = "Existing Onezone deployment resumed work."
MSG_AUTHENTICATION_ERROR = (
    "The launch script cannot access onepanel to manage the deployment process.\n"
    "Please ensure that valid emergency passphrase is present\n"
    f"in the {EMERGENCY_PASSPHRASE_VARIABLE} environment variable\n"
    "or oversee the cluster status manually."
)
MSG_MISSING_EXISTING_PASSPHRASE = (
    f"Environment variable {EMERGENCY_PASSPHRASE_VARIABLE} is missing.\n"
    "An existing deployment will continue to work\n"
    "but this script will not be able to track its startup.\n"
    "You can fix this by setting the variable\n"
    "to the Onepanel' passphrase (formerly admin account's password)."
)
MSG_MISSING_NEW_PASSPHRASE = (
    f"Environment variable {EMERGENCY_PASSPHRASE_VARIABLE} is missing.\n"
    "When deploying a new cluster this variable is required.\n"
    "Please set it to your desired Onepanel emergency passphrase.\n"
)
MSG_FAILURE_DUMP_LOGS = (
    "\n"
    "Below is a dump of all application logs at the moment of failure:\n"
    "-------------------------------------------------------------\n"
)
MSG_FAILURE_FOOTER = (
    "-------------------------------------------------------------\n"
    "ERROR: Starting the container failed - see above."
)

# Version upgrade check: we allow at most one major jump (with special cases for 25/26).
ONP_VERSION_FILE_PACKAGES_PATH = "/etc/oz_panel/deployed-version.json"
ONP_DEFAULT_ASSUMED_VERSION = "20.02.1"  # when version file is missing
ONP_RELEASES_PACKAGES_PATH = "/usr/lib/oz_panel/releases/RELEASES"
ONP_RELEASES_SOURCES_PATH = "_build/default/rel/oz_panel/releases/RELEASES"

# Persistence detection
COUCHBASE_DATA_DIR = "/opt/couchbase/var/lib/couchbase/data"


class MissingVariableError(Exception):
    """Indicates operation error caused by missing environment variable"""

    def __init__(self, variable_name):
        message = "Missing {} environment variable".format(variable_name)
        super(Exception, self).__init__(message)
        self.variable_name = variable_name


class AuthenticationError(Exception):
    """Indicates failure to execute an API request caused by rejected authentication"""

    pass


class Label(IntEnum):
    """
    Label specifiers for pre-releases.
    Ordered by precedence: alpha < beta < rc < stable (no label).
    """

    ALPHA = 1
    BETA = 2
    RC = 3
    STABLE = 4

    @classmethod
    def from_string(cls, s):
        if s == "alpha":
            return cls.ALPHA
        if s == "beta":
            return cls.BETA
        if s == "rc":
            return cls.RC
        raise ValueError(f"Unknown label: {s}")


class Revision(NamedTuple):
    """
    Represents a system revision based on Calendar Versioning.

    Format: YY.Minor[.Patch][-Label]

    Examples:
        25.0-alpha.1
        25.0
        25.0.1
    """

    year: int
    minor: int
    patch: int = 0
    label: Label = Label.STABLE
    label_ordinal: int = 0


class UpgradabilityCheckResult(Enum):
    """Result of comparing previous and new version for startup."""

    SAME_VERSION = 1
    ALLOWED_UPGRADE = 2
    UPGRADE_JUMP_TOO_BIG = 3
    DOWNGRADE = 4


def main():
    current_log_level = get_env("ONEPANEL_LOG_LEVEL", "info").lower()

    try:
        previous_version = assert_upgradability()

        preconfigure()
        start_onepanel()

        update_persisted_version(previous_version=previous_version)

        batch_mode = get_env("ONEPANEL_BATCH_MODE", "false")
        if batch_mode.lower() == "true":
            configure_deployment()

        # show_details()  NOTE: currently not working correctly (all details are null)
    except Exception as e:
        log("\nERROR: {0}".format(e))
        if get_env("ONEPANEL_DEBUG_MODE", "false").lower() == "true":
            pass
        else:
            log(MSG_FAILURE_DUMP_LOGS)
            print_logs(current_log_level, infinitely=False)
            log(MSG_FAILURE_FOOTER)
            sys.exit(1)

    previous_log_cursors = print_logs(current_log_level, infinitely=False)
    with open(SERVICE_READY_LOCK_FILE, "w"):
        pass
    print_logs(
        current_log_level, starting_log_cursors=previous_log_cursors, infinitely=True
    )


def assert_upgradability():
    """Check upgradability based on versions.

    Returns previous_version for persistence when not fresh install, None otherwise.
    Exits on disallowed upgrade or downgrade.
    """
    new_version = infer_new_version()

    if is_fresh_install():
        log(MSG_FRESH_DEPLOYMENT.format(new_version=new_version))
        return None

    prev_version = infer_previous_version()
    result = check_upgradability(prev_version, new_version)

    if result == UpgradabilityCheckResult.DOWNGRADE:
        log(
            MSG_DOWNGRADE.format(prev_version=prev_version, current_version=new_version)
        )
        sys.exit(1)

    elif result == UpgradabilityCheckResult.UPGRADE_JUMP_TOO_BIG:
        log(
            MSG_UPGRADE_JUMP_TOO_BIG.format(
                prev_version=prev_version,
                current_version=new_version,
            )
        )
        sys.exit(1)

    elif result == UpgradabilityCheckResult.SAME_VERSION:
        log(
            MSG_RESUME_SAME_VERSION.format(
                prev_version=prev_version,
                current_version=new_version,
            )
        )

    elif result == UpgradabilityCheckResult.ALLOWED_UPGRADE:
        log(
            MSG_RESUME_UPGRADE.format(
                prev_version=prev_version,
                current_version=new_version,
            )
        )

    return prev_version


def infer_new_version():
    """
    Parse RELEASES file and return the onepanel version string (e.g. "25.0").
    Exits with a message if file is missing or version pattern not found.
    """
    releases_path = ONP_RELEASES_PACKAGES_PATH
    if get_env(ONEPANEL_OVERRIDE):
        releases_path = os.path.join(
            get_env(ONEPANEL_OVERRIDE), ONP_RELEASES_SOURCES_PATH
        )

    if not os.path.isfile(releases_path):
        log(f"Could not find RELEASES file at {releases_path}")
        sys.exit(1)

    try:
        with open(releases_path, "r") as f:
            content = f.read()
        # e.g. {onepanel,"25.0","./lib/onepanel-25.0"}
        m = re.search(r'\{onepanel\s*,\s*["\']([^"\']+)["\']', content)
        if m:
            return m.group(1).strip()
    except OSError as e:
        log(f"Failed to read RELEASES file {releases_path}: {e}")
        sys.exit(1)

    log(f"Could not find onepanel version in RELEASES file: {releases_path}")
    sys.exit(1)


def infer_previous_version():
    try:
        with open(ONP_VERSION_FILE_PACKAGES_PATH, "r") as f:
            data = json.load(f)

        return data["current"]
    except (OSError, ValueError):
        log(MSG_COULD_NOT_RESOLVE_VERSION)
        time.sleep(SLEEP_COULD_NOT_RESOLVE_VERSION_SEC)

        return ONP_DEFAULT_ASSUMED_VERSION


def check_upgradability(prev_version_str, new_version_str):
    prev_rev = parse_revision(prev_version_str.strip())
    new_rev = parse_revision(new_version_str.strip())

    if new_rev < prev_rev:
        return UpgradabilityCheckResult.DOWNGRADE
    elif new_rev > prev_rev:
        if (new_rev.year - prev_rev.year) <= 1:
            return UpgradabilityCheckResult.ALLOWED_UPGRADE
        elif new_rev.year == 25 and prev_rev.year in (20, 21):
            return UpgradabilityCheckResult.ALLOWED_UPGRADE
        elif new_rev.year == 26 and prev_rev.year in (21, 25):
            return UpgradabilityCheckResult.ALLOWED_UPGRADE

        return UpgradabilityCheckResult.UPGRADE_JUMP_TOO_BIG

    return UpgradabilityCheckResult.SAME_VERSION


def parse_revision(version_str) -> Revision:
    try:
        # Handle empty string or None
        if not version_str:
            raise ValueError("Empty revision string")

        # Split main part and label
        parts = version_str.split("-", 1)
        main_part = parts[0]
        label_part = parts[1] if len(parts) > 1 else None

        # Parse numbers
        numbers = [int(n) for n in main_part.split(".")]
        if len(numbers) == 2:
            year, minor = numbers
            patch = 0
        elif len(numbers) == 3:
            year, minor, patch = numbers
        else:
            raise ValueError("Invalid version number format")

        # Parse label
        if label_part is None:
            label = Label.STABLE
            ordinal = 0
        else:
            if year > 21:
                # Modern format: label.ordinal (e.g., alpha.2)
                if "." not in label_part:
                    raise ValueError("Invalid modern label format")
                lbl_str, ord_str = label_part.split(".", 1)
                label = Label.from_string(lbl_str)
                ordinal = int(ord_str)
            else:
                # Legacy format: labelordinal (e.g., alpha2)
                match = re.match(r"([a-z]+)(\d+)", label_part)
                if not match:
                    raise ValueError("Invalid legacy label format")
                lbl_str, ord_str = match.groups()
                label = Label.from_string(lbl_str)
                ordinal = int(ord_str)

        return Revision(
            year=year, minor=minor, patch=patch, label=label, label_ordinal=ordinal
        )
    except Exception as e:
        raise ValueError(f"Invalid revision format '{version_str}': {e}") from e


def update_persisted_version(previous_version=None):
    """
    Write deployed-version.json. When previous_version is None (fresh deploy),
    only current is written. Otherwise, both previous and current are stored.
    """
    current = infer_new_version()
    data = {"current": current}
    if previous_version is not None:
        data["previous"] = previous_version

    os.makedirs(os.path.dirname(ONP_VERSION_FILE_PACKAGES_PATH), exist_ok=True)
    with open(ONP_VERSION_FILE_PACKAGES_PATH, "w") as f:
        json.dump(data, f, indent=4)


def preconfigure():
    upgrade_legacy_vm_args_if_exists()

    override_path = get_env(ONEPANEL_OVERRIDE)
    if override_path:
        app_config_path = os.path.join(override_path, ONP_GENERATED_CONFIG_SOURCES_PATH)
        vm_args_path = os.path.join(override_path, ONP_VM_ARGS_SOURCES_PATH)
    else:
        app_config_path = ONP_GENERATED_CONFIG_PACKAGES_PATH
        vm_args_path = ONP_VM_ARGS_PACKAGES_PATH

    if not config_file_initialized(app_config_path):
        generate_config_file(app_config_path)

    set_node_name(vm_args_path)


def upgrade_legacy_vm_args_if_exists():
    if get_env(ONEPANEL_OVERRIDE):
        legacy_vm_args_path_template = os.path.join(
            get_env(ONEPANEL_OVERRIDE),
            "../{component}",
            LEGACY_VM_ARGS_SOURCES_PATH_TEMPLATE,
        )
    else:
        legacy_vm_args_path_template = LEGACY_VM_ARGS_PACKAGES_PATH_TEMPLATE

    for component in COMPONENTS:
        legacy_vm_args_path = legacy_vm_args_path_template.format(component=component)

        if os.path.exists(legacy_vm_args_path):
            upgrade_legacy_vm_args(legacy_vm_args_path)


def upgrade_legacy_vm_args(legacy_vm_args_path):
    with open(legacy_vm_args_path, "r+") as f:
        content = f.read()
        node = re.search(r"-name (?P<node>.*)", content).group("node")
        cookie = re.search(r"-setcookie (?P<cookie>.*)", content).group("cookie")

    autogenerated_vm_args_path = os.path.join(
        os.path.dirname(legacy_vm_args_path), "autogenerated.vm.args"
    )

    with open(autogenerated_vm_args_path, "w+") as f:
        f.write(AUTOGENERATED_VM_ARGS_TEMPLATE.format(node=node, cookie=cookie))

    os.remove(legacy_vm_args_path)

    log(
        f"Upgraded legacy vm.args: {legacy_vm_args_path} -> {autogenerated_vm_args_path}"
    )


def config_file_initialized(file_path):
    try:
        with open(file_path, "r") as f:
            content = f.read()
            return bool(re.search(r"{config_initialized,\s*true}", content))
    except:
        return False


def generate_config_file(file_path):
    content = (
        "% MACHINE GENERATED FILE. DO NOT MODIFY.\n"
        "% Use overlay.config for custom configuration.\n\n"
        "[{onepanel, [{config_initialized, true}"
    )

    generate_test_web_cert = get_env("ONEPANEL_GENERATE_TEST_WEB_CERT")
    if generate_test_web_cert:
        domain = get_env("ONEPANEL_GENERATED_CERT_DOMAIN")
        flag = "true" if generate_test_web_cert == "true" else "false"
        content += ",\n{{generate_test_web_cert, {0}}}".format(flag)
        content += ',\n{{test_web_cert_domain, "{0}"}}'.format(domain)

    trust_test_ca = get_env("ONEPANEL_TRUST_TEST_CA")
    if trust_test_ca:
        flag = "true" if trust_test_ca == "true" else "false"
        content += ",\n{{treat_test_ca_as_trusted, {0}}}".format(flag)

    content += "\n]}]."

    with open(file_path, "w") as f:
        f.write(content)


def set_node_name(file_path):
    hostname = sp.check_output(["hostname", "-f"]).decode().rstrip("\n")
    replace(file_path, r"-name .*", "-name onepanel@{0}".format(hostname))


def start_onepanel():
    log("Starting oz_panel...")

    cmd = ["service", "oz_panel", "start"]
    if get_env(ONEPANEL_OVERRIDE):
        oz_panel_script = os.path.join(
            get_env(ONEPANEL_OVERRIDE), "_build/default/rel/oz_panel/bin/oz_panel"
        )
        cmd = [oz_panel_script, "start"]

    try:
        sp.check_output(cmd)
    except sp.CalledProcessError as err:
        log("ERROR: " + str(err))
        log("Output was:\n")
        log(str(err.output))
        sys.exit(err.returncode)

    wait_for_rest_listener()
    log("[  OK  ] oz_panel started\n")


def wait_for_rest_listener():
    first = True
    connected = False
    while not connected:
        try:
            requests.get("https://127.0.0.1:9443/api/v3/onepanel/", verify=False)
        except requests.ConnectionError:
            if first:
                log(
                    "Waiting for oz_panel server to be available\n"
                    "(may require starting other cluster nodes)\n"
                )
                first = False
            time.sleep(1)
        else:
            connected = True


def configure_deployment():
    batch_config = get_batch_config()
    try:
        if configure(batch_config):
            log(MSG_CONGRATULATIONS)
        else:
            log(MSG_WAITING_FOR_CLUSTER)
            wait_for_workers()
            log(MSG_RESUMED_WORK)
    except AuthenticationError:
        log(MSG_AUTHENTICATION_ERROR)
    except MissingVariableError as e:
        if e.variable_name != EMERGENCY_PASSPHRASE_VARIABLE:
            raise

        if is_fresh_install():
            # most likely this is an existing deployment
            log(MSG_MISSING_EXISTING_PASSPHRASE)
        else:
            log(MSG_MISSING_NEW_PASSPHRASE)


def get_batch_config():
    batch_config = get_env("ONEZONE_CONFIG", "")
    batch_config = yaml.safe_load(batch_config)
    if not batch_config:
        return {}

    # insert interactiveDeployment mark if not present
    onepanel_config = batch_config.get("onepanel", {})
    if "interactiveDeployment" not in onepanel_config:
        onepanel_config["interactiveDeployment"] = False
        batch_config["onepanel"] = onepanel_config

    return batch_config


def configure(config):
    """
    Attempts to deploy the Onezone
    :return: False if configuration was skipped because of existing deployment,
        True upon success
    """
    passphrase = get_emergency_passphrase()

    try:
        set_emergency_passphrase(passphrase)
    except AuthenticationError:
        # emergency passphrase setup failure indicates existing deployment
        return False

    r = do_auth_request(
        requests.post,
        "https://127.0.0.1:9443/api/v3/onepanel/zone/configuration",
        headers={"content-type": "application/x-yaml"},
        data=yaml.dump(config),
        verify=False,
    )

    if r.status_code == codes.conflict:
        return False

    if not r.ok:
        raise RuntimeError(
            "Failed to start configuration process, the response was:\n"
            "  code: {0}\n"
            "  body: {1}\n"
            "For more information please check the logs.".format(r.status_code, r.text)
        )

    loc = r.headers["location"]
    status = "running"
    steps = []
    resp = {}

    log("\nConfiguring Onezone:")
    while status == "running":
        r = do_auth_request(requests.get, "https://127.0.0.1:9443" + loc, verify=False)
        if not r.ok:
            raise RuntimeError(
                "Unexpected configuration error\n{0}"
                "For more information please check the logs.".format(r.text)
            )
        else:
            resp = json.loads(r.text)
            status = resp.get("status", "error")
            for step in resp.get("steps", []):
                if steps and step == steps[0]:
                    steps = steps[1:]
                else:
                    log(format_step(step))
            steps = resp.get("steps", [])
            time.sleep(1)

    if status != "ok":
        raise RuntimeError(format_error(resp))
    return True


def get_emergency_passphrase():
    """Returns emergency passphrase provided in environment variable"""
    passphrase = get_env(EMERGENCY_PASSPHRASE_VARIABLE)
    if passphrase is None:
        raise MissingVariableError(EMERGENCY_PASSPHRASE_VARIABLE)
    return passphrase


def set_emergency_passphrase(passphrase):
    r = requests.put(
        "https://127.0.0.1:9443/api/v3/onepanel/emergency_passphrase",
        headers={"content-type": "application/json"},
        data=json.dumps({"newPassphrase": passphrase}),
        verify=False,
    )
    if r.status_code in (codes.unauthorized, codes.forbidden):
        raise AuthenticationError(
            "Could not set Onepanel emergency passphrase due to "
            "authentication error: {} {}".format(r.status_code, r.text)
        )
    if not r.ok:
        raise RuntimeError(
            "Could not set Onepanel emergency passphrase: {} {}".format(
                r.status_code, r.text
            )
        )


def do_auth_request(request, *args, **kwargs):
    passphrase = get_emergency_passphrase()
    r = request(*args, auth=(PASSPHRASE_USERNAME, passphrase), **kwargs)
    if r.status_code in (codes.unauthorized, codes.forbidden):
        raise AuthenticationError(
            "Authentication error.\n"
            "Please ensure that valid emergency passphrase is present\n"
            "in the {} environment variable".format(EMERGENCY_PASSPHRASE_VARIABLE)
        )
    return r


def wait_for_workers():
    url = "https://127.0.0.1:9443/api/v3/onepanel/zone/nagios"
    retries = 0
    while not nagios_up(url, retries % 10 == 9):
        time.sleep(1)
        retries += 1
        if retries == 120:
            raise RuntimeError("Timeout waiting for the Onepanel service readiness")


def nagios_up(url, log_errors=False):
    try:
        r = do_auth_request(requests.get, url, verify=False)
        if not r.ok:
            if log_errors:
                log(
                    "Onepanel service is reachable, but nagios is not reporting an OK status - retrying..."
                )
            return False
    except Exception:
        if log_errors:
            log("Onepanel service is not reachable - retrying...")
        return False

    healthdata = eTree.fromstring(r.text)
    return healthdata.attrib["status"] == "ok"


def show_details():
    log("\nContainer details:")

    container_id = get_container_id()
    container_info = inspect_container(container_id)

    show_ip_address(container_info)
    show_ports(container_info)


def get_container_id():
    with open("/proc/self/cgroup", "r") as f:
        return f.readline().split("/")[-1].rstrip("\n")


def inspect_container(container_id):
    try:
        result = sp.check_output(
            [
                "curl",
                "-s",
                "--unix-socket",
                "/var/run/docker.sock",
                "http:/containers/{0}/json".format(container_id),
            ]
        )
        return json.loads(result)
    except Exception:
        return {}


def show_ip_address(json):
    ip = "-"
    try:
        ip = sp.check_output(["hostname", "-i"]).rstrip("\n")
        ip = list(json["NetworkSettings"]["Networks"].items())[0][1]["IPAddress"]
    except Exception:
        pass
    log("* IP Address: {0}".format(ip))


def show_ports(json):
    ports = json.get("NetworkSettings", {}).get("Ports", {})
    ports_format = []
    for container_port in ports:
        host = ports[container_port]
        if host:
            for host_port in host:
                ports_format.append(
                    "{0}:{1} -> {2}".format(
                        host_port["HostIp"], host_port["HostPort"], container_port
                    )
                )
        else:
            ports_format.append(container_port)
    ports_str = "\n         ".join(ports_format) if ports_format else "-"
    log("* Ports: {0}".format(ports_str))


def format_step(step):
    service, action = step.split(":")
    return "* {0}: {1}".format(service, action)


def format_error(response):
    if "error" not in response:
        return "Error: unexpected server response"
    error_obj = response["error"]
    error_id, descr, details, nodes = unwrap_error_with_hosts(error_obj)
    details_str = format_dict(details, "    ")

    if details_str:
        details_str = "  details:\n" + details_str
    nodes_str = ""
    if nodes:
        nodes_str = "  nodes:\n    " + "\n    ".join(sorted(nodes))
    descr_str = textwrap.fill(
        "description: " + descr,
        initial_indent="  ",
        subsequent_indent="    ",
        **WRAP_KWARGS,
    )
    return "Error:\n  id: {}\n{}\n{}\n{}".format(
        error_id, nodes_str, descr_str, details_str
    )


def format_dict(details, indent):
    result = ""
    for key, value in list(details.items()):
        if isinstance(value, dict):
            result += indent + "{}:\n".format(key)
            result += format_dict(value, indent + "  ")
        else:
            result += (
                textwrap.fill(
                    "{}: {}".format(key, value),
                    initial_indent=indent,
                    subsequent_indent=indent + "  ",
                    **WRAP_KWARGS,
                )
                + "\n"
            )
    return result


def unwrap_error_with_hosts(error_obj):
    """Extracts original error from a wrapper listing hosts
    where the error occurred"""
    error_id = error_obj.get("id")
    description = error_obj.get("description")
    details = error_obj.get("details", {})
    nodes = []

    if error_id == "errorOnNodes" and "error" in details:
        error_id = details["error"]["id"]
        description = details["error"]["description"]
        nodes = details["hostnames"]
        details = details["error"].get("details", {})

    return error_id, description, details, nodes


def print_logs(log_level, starting_log_cursors=None, infinitely=True):
    # first run of the function
    if not isinstance(starting_log_cursors, list):
        starting_log_cursors = []
        if log_level in LOG_LEVELS:
            log("\nLogging on '{0}' level:".format(log_level))
            for log_prefix, log_dir in LOGS:
                log_file = os.path.join(log_dir, log_level + ".log")
                starting_log_cursors.append((log_prefix, log_file, None, None))
        else:
            log("\nLogging to stdout disabled (log level = {})".format(log_level))

    new_log_cursors = print_new_logs(starting_log_cursors)
    while infinitely:
        new_log_cursors = print_new_logs(new_log_cursors)
        time.sleep(1)
    return new_log_cursors


def print_new_logs(log_cursors):
    new_logs = []

    for log_prefix, log_file, log_fd, log_ino in log_cursors:
        try:
            if os.stat(log_file).st_ino != log_ino:
                if log_fd:
                    log_fd.close()
                log_fd = open(log_file, "r")
                log_ino = os.stat(log_file).st_ino

            log_line = log_fd.readline()
            while log_line:
                log("{0} {1}".format(log_prefix, log_line), end="")
                log_line = log_fd.readline()

            new_logs.append((log_prefix, log_file, log_fd, log_ino))
        except:
            new_logs.append((log_prefix, log_file, None, None))

    return new_logs


def is_fresh_install():
    """True if there is no preexisting persistence (fresh deployment)."""
    return not os.path.isdir(COUCHBASE_DATA_DIR)


def log(message, end="\n"):
    sys.stdout.write(message + end)
    sys.stdout.flush()


def replace(file_path, pattern, value):
    with open(file_path, "r+") as f:
        content = f.read()
        content = re.sub(pattern, value, content)
        f.seek(0)
        f.truncate()
        f.write(content)


def get_env(key, default=None):
    return os.environ.get(key, default)


if __name__ == "__main__":
    main()
