#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import os
import re
import subprocess as sp
import sys
import time
from enum import Enum, IntEnum
from dataclasses import dataclass

import textwrap
import yaml
import requests
from requests import codes
from requests.packages.urllib3.exceptions import InsecureRequestWarning

try:
    import xml.etree.cElementTree as eTree
except ImportError:
    import xml.etree.ElementTree as eTree

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)


COMPONENTS = ['cluster_manager', 'oz_panel', 'oz_worker']

LOGS = [('[oz_panel]', '/var/log/oz_panel'),
        ('[cluster_manager]', '/var/log/cluster_manager'),
        ('[oz_worker]', '/var/log/oz_worker')]
LOG_LEVELS = ['debug', 'info', 'error']

# If onepanel is started from sources, contains the path to the root directory
# of the pre-built onepanel repo/artifact.
ONEPANEL_OVERRIDE = 'ONEPANEL_OVERRIDE'

# Username to be used in Basic auth with the emergency passphrase
PASSPHRASE_USERNAME = 'onepanel'
EMERGENCY_PASSPHRASE_VARIABLE = 'ONEPANEL_EMERGENCY_PASSPHRASE'

LEGACY_VM_ARGS_SOURCES_PATH_TEMPLATE = '_build/default/rel/{component}/etc/vm.args'

ONP_GENERATED_CONFIG_SOURCES_PATH = '_build/default/rel/oz_panel/etc/autogenerated.config'
ONP_VM_ARGS_SOURCES_PATH = '_build/default/rel/oz_panel/etc/autogenerated.vm.args'

LEGACY_VM_ARGS_PACKAGES_PATH_TEMPLATE = '/etc/{component}/vm.args'

ONP_GENERATED_CONFIG_PACKAGES_PATH = '/etc/oz_panel/autogenerated.config'
ONP_VM_ARGS_PACKAGES_PATH = '/etc/oz_panel/autogenerated.vm.args'

AUTOGENERATED_VM_ARGS_TEMPLATE = '''# MACHINE GENERATED FILE. DO NOT MODIFY.

## Name of the node
-name {node}

## Cookie for distributed erlang
-setcookie {cookie}
'''

COULD_NOT_RESOLVE_VERSION_LOG_MSG = '''Could not resolve the previously deployed software version;
for versions < 25.1, this information is not supported. Assuming the previously running
version was NOT LOWER THAN 20.02.1.

WARNING: if you are upgrading from version 19.02.* or lower, STOP the deployment
and first upgrade to 20.02.*. Otherwise, let it continue.

Sleeping for 30 seconds to let you react...
'''

COULD_NOT_RESOLVE_VERSION_SLEEP_PERIOD_SEC = 30

MSG_FRESH_DEPLOYMENT = '''No previous persistence detected.

This is a fresh deployment of Onezone in version {new_onp_version}
'''

MSG_RESUME_SAME_VERSION = '''Preexisting persistence has been detected, version {prev_onp_version}

Resuming Onezone in version {current_onp_version} ...
'''

MSG_RESUME_UPGRADE = '''Preexisting persistence has been detected, version {prev_onp_version}

Resuming Onezone in version {current_onp_version} - an upgrade will be performed
during the startup of services. Please allow more time until the services are operational.

You may monitor the logs for details (paths inside the container):
/var/log/oz_panel/info.log
/var/log/oz_worker/info.log
'''

MSG_UPGRADE_JUMP_TOO_BIG = '''Preexisting persistence has been detected, version {prev_onp_version}

ERROR: You are attempting to run Onezone in version {current_onp_version}
Upgrading by more than one major versions is not supported. Please upgrade to
an intermediate major version first, then start this version. Note that majors
21 and 25 are treated as the same one, due to reworked naming convention.

Exemplary allowed upgrades:
    21.02.8 -> 25.0
    21.02.2 -> 26.0
    25.0 -> 25.1
    25.1 -> 26.1
    20.02.6 -> 25.1

Exemplary disallowed upgrades:
    20.02.20 -> 26.0  (upgrade to 21.02.* / 25.* first)
'''

MSG_DOWNGRADE = '''Preexisting persistence has been detected, version {prev_onp_version}

ERROR: You are attempting to run Onezone in version {current_onp_version}
Downgrades are not supported. Please use Onezone in version {prev_onp_version}
or newer.
'''

WRAP_KWARGS = {
    'width': 100,
    'break_long_words': False,
    'break_on_hyphens': False
}

SERVICE_READY_LOCK_FILE = '/root/service-ready.lock'  # used by the "await" script

# Version upgrade check: we allow at most one major jump (with special cases for 25/26).
ONP_VERSION_FILE_PACKAGES_PATH = '/etc/oz_panel/deployed-version.json'
ONP_DEFAULT_ASSUMED_VERSION = '20.02.1'  # when version file is missing
ONP_RELEASES_PACKAGES_PATH = '/usr/lib/oz_panel/releases/RELEASES'
ONP_RELEASES_SOURCES_PATH = '_build/default/rel/oz_panel/releases/RELEASES'

# Persistence detection
COUCHBASE_DATA_DIR = '/opt/couchbase/var/lib/couchbase/data'


class VersionCheckResult(Enum):
    """Result of comparing previous and new version for startup."""
    SAME_VERSION = 1
    ALLOWED_UPGRADE = 2
    UPGRADE_JUMP_TOO_BIG = 3
    DOWNGRADE = 4


class Label(IntEnum):
    """
    Label specifiers for pre-releases.
    Ordered by precedence: alpha < beta < rc < stable (no label).
    """

    ALPHA = 1
    BETA = 2
    RC = 3
    STABLE = 4

    @classmethod
    def from_string(cls, s):
        if s == "alpha":
            return cls.ALPHA
        if s == "beta":
            return cls.BETA
        if s == "rc":
            return cls.RC
        raise ValueError(f"Unknown label: {s}")

    def __str__(self) -> str:
        if self == self.ALPHA:
            return "alpha"
        if self == self.BETA:
            return "beta"
        if self == self.RC:
            return "rc"
        return ""


@dataclass
class Revision:
    """
    Represents a system revision based on Calendar Versioning.

    Format: YY.Minor[.Patch][-Label]

    Examples:
        25.0-alpha.1
        25.0
        25.0.1
    """

    year: int
    minor: int
    patch: int = 0
    label: Label = Label.STABLE
    label_ordinal: int = 0

    @property
    def major(self):
        """Compatibility property for old major version (year)."""
        return str(self.year)

    @classmethod
    def parse(cls, revision_str):
        """Parse a revision string into a Revision object."""
        try:
            # Handle empty string or None
            if not revision_str:
                raise ValueError("Empty revision string")

            # Split main part and label
            parts = revision_str.split("-", 1)
            main_part = parts[0]
            label_part = parts[1] if len(parts) > 1 else None

            # Parse numbers
            numbers = [int(n) for n in main_part.split(".")]
            if len(numbers) == 2:
                year, minor = numbers
                patch = 0
            elif len(numbers) == 3:
                year, minor, patch = numbers
            else:
                raise ValueError("Invalid version number format")

            # Parse label
            if label_part is None:
                label = Label.STABLE
                ordinal = 0
            else:
                if year > 21:
                    # Modern format: label.ordinal (e.g., alpha.2)
                    if "." not in label_part:
                        raise ValueError("Invalid modern label format")
                    lbl_str, ord_str = label_part.split(".", 1)
                    label = Label.from_string(lbl_str)
                    ordinal = int(ord_str)
                else:
                    # Legacy format: labelordinal (e.g., alpha2)
                    match = re.match(r"([a-z]+)(\d+)", label_part)
                    if not match:
                        raise ValueError("Invalid legacy label format")
                    lbl_str, ord_str = match.groups()
                    label = Label.from_string(lbl_str)
                    ordinal = int(ord_str)

            return cls(
                year=year, minor=minor, patch=patch, label=label, label_ordinal=ordinal
            )
        except Exception as e:
            raise ValueError(f"Invalid revision format '{revision_str}': {e}") from e

    def get_release_line(self) -> str:
        """Returns concatenated major and minor version, e.g. '21.02' or '25.0'."""
        if self.year <= 21:
            return f"{self.year}.{self.minor:02d}"
        return f"{self.year}.{self.minor}"

    def __str__(self) -> str:
        # Main part
        if self.year <= 21:
            s = f"{self.year}.{self.minor:02d}"
        else:
            s = f"{self.year}.{self.minor}"

        if self.patch > 0 or self.year <= 21:
            s += f".{self.patch}"

        # Label part
        if self.label != Label.STABLE:
            s += "-"
            if self.year > 21:
                s += f"{self.label}.{self.label_ordinal}"
            else:
                s += f"{self.label}{self.label_ordinal}"

        return s

    def __hash__(self):
        return hash(str(self))

    def __repr__(self):
        return f"Revision({str(self)})"

    def _cmp_tuple(self):
        return self.year, self.minor, self.patch, self.label.value, self.label_ordinal

    def __eq__(self, other):
        if not isinstance(other, Revision):
            return NotImplemented
        return self._cmp_tuple() == other._cmp_tuple()

    def __lt__(self, other):
        if not isinstance(other, Revision):
            return NotImplemented
        return self._cmp_tuple() < other._cmp_tuple()

    def __le__(self, other):
        if not isinstance(other, Revision):
            return NotImplemented
        return self._cmp_tuple() <= other._cmp_tuple()

    def __gt__(self, other):
        if not isinstance(other, Revision):
            return NotImplemented
        return self._cmp_tuple() > other._cmp_tuple()

    def __ge__(self, other):
        if not isinstance(other, Revision):
            return NotImplemented
        return self._cmp_tuple() >= other._cmp_tuple()


class MissingVariableError(Exception):
    """Indicates operation error caused by missing environment variable"""
    def __init__(self, variable_name):
        message = "Missing {} environment variable".format(variable_name)
        super(Exception, self).__init__(message)
        self.variable_name = variable_name


class AuthenticationError(Exception):
    """Indicates failure to execute an API request caused by rejected authentication"""
    pass


def log(message, end='\n'):
    sys.stdout.write(message + end)
    sys.stdout.flush()


def replace(file_path, pattern, value):
    with open(file_path, 'r+') as f:
        content = f.read()
        content = re.sub(pattern, value, content)
        f.seek(0)
        f.truncate()
        f.write(content)


def set_node_name(file_path):
    hostname = sp.check_output(['hostname', '-f']).decode().rstrip('\n')
    replace(file_path, r'-name .*', '-name onepanel@{0}'.format(hostname))


def config_file_initialized(file_path):
    try:
        with open(file_path, 'r') as f:
            content = f.read()
            return bool(re.search(r'{config_initialized,\s*true}', content))
    except:
        return False


def generate_config_file(file_path):
    content = ('% MACHINE GENERATED FILE. DO NOT MODIFY.\n'
               '% Use overlay.config for custom configuration.\n\n'
               '[{onepanel, [{config_initialized, true}')

    generate_test_web_cert = os.environ.get('ONEPANEL_GENERATE_TEST_WEB_CERT')
    if generate_test_web_cert:
        domain = os.environ.get('ONEPANEL_GENERATED_CERT_DOMAIN')
        flag = 'true' if generate_test_web_cert == 'true' else 'false'
        content += ',\n{{generate_test_web_cert, {0}}}'.format(flag)
        content += ',\n{{test_web_cert_domain, "{0}"}}'.format(domain)

    trust_test_ca = os.environ.get('ONEPANEL_TRUST_TEST_CA')
    if trust_test_ca:
        flag = 'true' if trust_test_ca == 'true' else 'false'
        content += ',\n{{treat_test_ca_as_trusted, {0}}}'.format(flag)

    content += '\n]}].'

    with open(file_path, 'w') as f:
        f.write(content)


def start_onepanel():
    log('Starting oz_panel...')

    cmd = ['service', 'oz_panel', 'start']
    if os.environ.get(ONEPANEL_OVERRIDE):
        oz_panel_script = os.path.join(
            os.environ.get(ONEPANEL_OVERRIDE),
            "_build/default/rel/oz_panel/bin/oz_panel"
        )
        cmd = [oz_panel_script, 'start']

    try:
        sp.check_output(cmd)
    except sp.CalledProcessError as err:
        log('ERROR: ' + str(err))
        log('Output was:\n')
        log(str(err.output))
        sys.exit(err.returncode)

    wait_for_rest_listener()
    log('[  OK  ] oz_panel started\n')


def wait_for_rest_listener():
    first = True
    connected = False
    while not connected:
        try:
            requests.get('https://127.0.0.1:9443/api/v3/onepanel/', verify=False)
        except requests.ConnectionError:
            if first:
                log('Waiting for oz_panel server to be available\n'
                    '(may require starting other cluster nodes)\n')
                first = False
            time.sleep(1)
        else:
            connected = True


def format_step(step):
    service, action = step.split(':')
    return '* {0}: {1}'.format(service, action)


def get_emergency_passphrase():
    """Returns emergency passphrase provided in environment variable"""
    passphrase = os.environ.get(EMERGENCY_PASSPHRASE_VARIABLE)
    if passphrase is None:
        raise MissingVariableError(EMERGENCY_PASSPHRASE_VARIABLE)
    return passphrase


def set_emergency_passphrase(passphrase):
    r = requests.put('https://127.0.0.1:9443/api/v3/onepanel/emergency_passphrase',
                     headers={'content-type': 'application/json'},
                     data=json.dumps({'newPassphrase': passphrase}),
                     verify=False)
    if r.status_code in (codes.unauthorized, codes.forbidden):
        raise AuthenticationError('Could not set Onepanel emergency passphrase due to '
                                  'authentication error: {} {}'
                                  .format(r.status_code, r.text))
    if not r.ok:
        raise RuntimeError('Could not set Onepanel emergency passphrase: {} {}'
                           .format(r.status_code, r.text))


def do_auth_request(request, *args, **kwargs):
    passphrase = get_emergency_passphrase()
    r = request(*args, auth=(PASSPHRASE_USERNAME, passphrase), **kwargs)
    if r.status_code in (codes.unauthorized, codes.forbidden):
        raise AuthenticationError('Authentication error.\n'
                                  'Please ensure that valid emergency passphrase is present\n'
                                  'in the {} environment variable'
                                  .format(EMERGENCY_PASSPHRASE_VARIABLE))
    return r


def get_batch_config():
    batch_config = os.environ.get('ONEZONE_CONFIG', '')
    batch_config = yaml.safe_load(batch_config)
    if not batch_config:
        return {}

    # insert interactiveDeployment mark if not present
    onepanel_config = batch_config.get('onepanel', {})
    if 'interactiveDeployment' not in onepanel_config:
        onepanel_config['interactiveDeployment'] = False
        batch_config['onepanel'] = onepanel_config

    return batch_config


def configure(config):
    """
    Attempts to deploy the Onezone
    :return: False if configuration was skipped because of existing deployment,
        True upon success
    """
    passphrase = get_emergency_passphrase()

    try:
        set_emergency_passphrase(passphrase)
    except AuthenticationError:
        # emergency passphrase setup failure indicates existing deployment
        return False

    r = do_auth_request(requests.post,
                        'https://127.0.0.1:9443/api/v3/onepanel/zone/configuration',
                        headers={'content-type': 'application/x-yaml'},
                        data=yaml.dump(config),
                        verify=False)

    if r.status_code == codes.conflict:
        return False

    if not r.ok:
        raise RuntimeError(
            'Failed to start configuration process, the response was:\n'
            '  code: {0}\n'
            '  body: {1}\n'
            'For more information please check the logs.'
            .format(r.status_code, r.text))

    loc = r.headers['location']
    status = 'running'
    steps = []
    resp = {}

    log('\nConfiguring Onezone:')
    while status == 'running':
        r = do_auth_request(requests.get,
                            'https://127.0.0.1:9443' + loc,
                            verify=False)
        if not r.ok:
            raise RuntimeError('Unexpected configuration error\n{0}'
                               'For more information please check the logs.'
                               .format(r.text))
        else:
            resp = json.loads(r.text)
            status = resp.get('status', 'error')
            for step in resp.get('steps', []):
                if steps and step == steps[0]:
                    steps = steps[1:]
                else:
                    log(format_step(step))
            steps = resp.get('steps', [])
            time.sleep(1)

    if status != 'ok':
        raise RuntimeError(format_error(resp))
    return True


def format_error(response):
    if 'error' not in response:
        return "Error: unexpected server response"
    error_obj = response['error']
    error_id, descr, details, nodes = unwrap_error_with_hosts(error_obj)
    details_str = format_dict(details, '    ')

    if details_str:
        details_str = '  details:\n' + details_str
    nodes_str = ''
    if nodes:
        nodes_str = '  nodes:\n    ' + '\n    '.join(sorted(nodes))
    descr_str = textwrap.fill('description: ' + descr, initial_indent='  ',
                              subsequent_indent='    ', **WRAP_KWARGS)
    return "Error:\n  id: {}\n{}\n{}\n{}".format(
        error_id, nodes_str, descr_str, details_str)


def format_dict(details, indent):
    result = ''
    for key, value in list(details.items()):
        if isinstance(value, dict):
            result += indent + '{}:\n'.format(key)
            result += format_dict(value, indent + '  ')
        else:
            result += textwrap.fill('{}: {}'.format(key, value),
                                    initial_indent=indent,
                                    subsequent_indent=indent + '  ',
                                    **WRAP_KWARGS) + '\n'
    return result


def unwrap_error_with_hosts(error_obj):
    """Extracts original error from a wrapper listing hosts
    where the error occurred"""
    error_id = error_obj.get('id')
    description = error_obj.get('description')
    details = error_obj.get('details', {})
    nodes = []

    if error_id == 'errorOnNodes' and 'error' in details:
        error_id = details['error']['id']
        description = details['error']['description']
        nodes = details['hostnames']
        details = details['error'].get('details', {})

    return error_id, description, details, nodes


def wait_for_workers():
    url = 'https://127.0.0.1:9443/api/v3/onepanel/zone/nagios'
    retries = 0
    while not nagios_up(url, retries % 10 == 9):
        time.sleep(1)
        retries += 1
        if retries == 120:
            raise RuntimeError('Timeout waiting for the Onepanel service readiness')


def nagios_up(url, log_errors=False):
    try:
        r = do_auth_request(requests.get, url, verify=False)
        if not r.ok:
            if log_errors:
                log('Onepanel service is reachable, but nagios is not reporting an OK status - retrying...')
            return False
    except Exception:
        if log_errors:
            log('Onepanel service is not reachable - retrying...')
        return False

    healthdata = eTree.fromstring(r.text)
    return healthdata.attrib['status'] == 'ok'


def get_container_id():
    with open('/proc/self/cgroup', 'r') as f:
        return f.readline().split('/')[-1].rstrip('\n')


def inspect_container(container_id):
    try:
        result = sp.check_output([
            'curl', '-s', '--unix-socket',
            '/var/run/docker.sock',
            'http:/containers/{0}/json'.format(container_id)
        ])
        return json.loads(result)
    except Exception:
        return {}


def show_ip_address(json):
    ip = '-'
    try:
        ip = sp.check_output(['hostname', '-i']).rstrip('\n')
        ip = list(json['NetworkSettings']['Networks'].items())[0][1]['IPAddress']
    except Exception:
        pass
    log('* IP Address: {0}'.format(ip))


def show_ports(json):
    ports = json.get('NetworkSettings', {}).get('Ports', {})
    ports_format = []
    for container_port in ports:
        host = ports[container_port]
        if host:
            for host_port in host:
                ports_format.append('{0}:{1} -> {2}'.format(
                    host_port['HostIp'], host_port['HostPort'], container_port
                ))
        else:
            ports_format.append(container_port)
    ports_str = '\n         '.join(ports_format) if ports_format else '-'
    log('* Ports: {0}'.format(ports_str))


def show_details():
    log('\nContainer details:')

    container_id = get_container_id()
    json = inspect_container(container_id)

    show_ip_address(json)
    show_ports(json)


def print_logs(log_level, starting_log_cursors=None, infinitely=True):
    # first run of the function
    if not isinstance(starting_log_cursors, list):
        starting_log_cursors = []
        if log_level in LOG_LEVELS:
            log('\nLogging on \'{0}\' level:'.format(log_level))
            for log_prefix, log_dir in LOGS:
                log_file = os.path.join(log_dir, log_level + '.log')
                starting_log_cursors.append((log_prefix, log_file, None, None))
        else:
            log('\nLogging to stdout disabled (log level = {})'.format(log_level))

    new_log_cursors = print_new_logs(starting_log_cursors)
    while infinitely:
        new_log_cursors = print_new_logs(new_log_cursors)
        time.sleep(1)
    return new_log_cursors


def print_new_logs(log_cursors):
    new_logs = []

    for log_prefix, log_file, log_fd, log_ino in log_cursors:
        try:
            if os.stat(log_file).st_ino != log_ino:
                if log_fd:
                    log_fd.close()
                log_fd = open(log_file, 'r')
                log_ino = os.stat(log_file).st_ino

            log_line = log_fd.readline()
            while log_line:
                log('{0} {1}'.format(log_prefix, log_line), end='')
                log_line = log_fd.readline()

            new_logs.append((log_prefix, log_file, log_fd, log_ino))
        except:
            new_logs.append((log_prefix, log_file, None, None))

    return new_logs


def upgrade_legacy_vm_args_if_exists():
    if os.environ.get(ONEPANEL_OVERRIDE):
        legacy_vm_args_path_template = os.path.join(
            os.environ.get(ONEPANEL_OVERRIDE), 
            '../{component}',
            LEGACY_VM_ARGS_SOURCES_PATH_TEMPLATE
        )
    else:
        legacy_vm_args_path_template = LEGACY_VM_ARGS_PACKAGES_PATH_TEMPLATE

    for component in COMPONENTS:
        legacy_vm_args_path = legacy_vm_args_path_template.format(component=component)

        if os.path.exists(legacy_vm_args_path):
            upgrade_legacy_vm_args(legacy_vm_args_path)


def upgrade_legacy_vm_args(legacy_vm_args_path):
    with open(legacy_vm_args_path, 'r+') as f:
        content = f.read()
        node = re.search(r'-name (?P<node>.*)', content).group('node')
        cookie = re.search(r'-setcookie (?P<cookie>.*)', content).group('cookie')

    autogenerated_vm_args_path = os.path.join(os.path.dirname(legacy_vm_args_path), 
                                              'autogenerated.vm.args')

    with open(autogenerated_vm_args_path, 'w+') as f:
        f.write(AUTOGENERATED_VM_ARGS_TEMPLATE.format(node=node, cookie=cookie))

    os.remove(legacy_vm_args_path)

    log(f'Upgraded legacy vm.args: {legacy_vm_args_path} -> {autogenerated_vm_args_path}')


def check_upgradability():
    """Check upgradability based on versions.

    Returns previous_version for persistence when not fresh install, None otherwise.
    Exits on disallowed upgrade or downgrade.
    """
    new_version = infer_new_version()

    if is_fresh_install():
        log(MSG_FRESH_DEPLOYMENT.format(new_onp_version=new_version))
        return None

    prev_version = infer_previous_version()
    result = compare_version(prev_version, new_version)

    if result == VersionCheckResult.DOWNGRADE:
        log(MSG_DOWNGRADE.format(
            prev_onp_version=prev_version,
            current_onp_version=new_version,
        ))
        sys.exit(1)

    elif result == VersionCheckResult.UPGRADE_JUMP_TOO_BIG:
        log(MSG_UPGRADE_JUMP_TOO_BIG.format(
            prev_onp_version=prev_version,
            current_onp_version=new_version,
        ))
        sys.exit(1)

    elif result == VersionCheckResult.SAME_VERSION:
        log(MSG_RESUME_SAME_VERSION.format(
            prev_onp_version=prev_version,
            current_onp_version=new_version,
        ))

    elif result == VersionCheckResult.ALLOWED_UPGRADE:
        log(MSG_RESUME_UPGRADE.format(
            prev_onp_version=prev_version,
            current_onp_version=new_version,
        ))

    return prev_version


def is_fresh_install():
    """True if there is no preexisting persistence (fresh deployment)."""
    return not os.path.isdir(COUCHBASE_DATA_DIR)


def infer_previous_version():
    try:
        with open(ONP_VERSION_FILE_PACKAGES_PATH, 'r') as f:
            data = json.load(f)
        return data['current']
    except (OSError, ValueError):
        log(COULD_NOT_RESOLVE_VERSION_LOG_MSG)
        time.sleep(COULD_NOT_RESOLVE_VERSION_SLEEP_PERIOD_SEC)

        return ONP_DEFAULT_ASSUMED_VERSION


def infer_new_version():
    """
    Parse RELEASES file and return the onepanel version string (e.g. "25.0").
    Exits with a message if file is missing or version pattern not found.
    """
    releases_path = ONP_RELEASES_PACKAGES_PATH
    if os.environ.get(ONEPANEL_OVERRIDE):
        releases_path = os.path.join(
            os.environ.get(ONEPANEL_OVERRIDE),
            ONP_RELEASES_SOURCES_PATH
        )
    if not os.path.isfile(releases_path):
        log('Could not find RELEASES file at {}'.format(releases_path))
        sys.exit(1)

    try:
        with open(releases_path, 'r') as f:
            content = f.read()
        # e.g. {onepanel,"25.0","./lib/onepanel-25.0"}
        m = re.search(r'\{onepanel\s*,\s*["\']([^"\']+)["\']', content)
        if m:
            return m.group(1).strip()
    except OSError as e:
        log('Failed to read RELEASES file {}: {}'.format(releases_path, e))
        sys.exit(1)

    log('Could not find onepanel version in RELEASES file: {}'.format(releases_path))
    sys.exit(1)


def compare_version(prev_version_str, new_version_str):
    """
    Compare previous (persisted) and new (installed) version using Revision.
    Returns VersionCheckResult: SAME_VERSION, ALLOWED_UPGRADE,
    UPGRADE_JUMP_TOO_BIG, or DOWNGRADE.
    """
    prev_rev = Revision.parse(prev_version_str.strip())
    new_rev = Revision.parse(new_version_str.strip())
    if new_rev < prev_rev:
        return VersionCheckResult.DOWNGRADE
    if new_rev > prev_rev:
        if _major_upgrade_allowed(prev_rev.year, new_rev.year):
            return VersionCheckResult.ALLOWED_UPGRADE
        return VersionCheckResult.UPGRADE_JUMP_TOO_BIG
    return VersionCheckResult.SAME_VERSION


def _major_upgrade_allowed(prev_major, new_major):
    """
    Whether a major-version upgrade is allowed.
    - To 25: both 20 and 21 can go. To 26: from 21 or 25. From 27: step <= 1.
    """
    if new_major <= prev_major:
        return True
    if new_major == 25:
        return prev_major in (20, 21)
    if new_major == 26:
        return prev_major in (21, 25)
    return (new_major - prev_major) <= 1


def parse_major_version(version_str):
    """Extract major version number (year). '20.02.1' -> 20, '25.0' -> 25. (Public for tests/logging.)"""
    return Revision.parse(version_str.strip()).year


def update_persisted_version(previous_version=None):
    """
    Write deployed-version.json. When previous_version is None (fresh deploy),
    only current is written. Otherwise both previous and current are stored.
    """
    current = infer_new_version()
    data = {'current': current}
    if previous_version is not None:
        data['previous'] = previous_version

    os.makedirs(os.path.dirname(ONP_VERSION_FILE_PACKAGES_PATH), exist_ok=True)
    with open(ONP_VERSION_FILE_PACKAGES_PATH, 'w') as f:
        json.dump(data, f, indent=2)


if __name__ == '__main__':
    current_log_level = os.environ.get('ONEPANEL_LOG_LEVEL', 'info').lower()
    try:
        previous_version = check_upgradability()
        upgrade_legacy_vm_args_if_exists()

        if os.environ.get(ONEPANEL_OVERRIDE):
            app_config_path = os.path.join(os.environ.get(ONEPANEL_OVERRIDE),
                                           ONP_GENERATED_CONFIG_SOURCES_PATH)

            vm_args_path = os.path.join(os.environ.get(ONEPANEL_OVERRIDE),
                                        ONP_VM_ARGS_SOURCES_PATH)
        else:
            app_config_path = ONP_GENERATED_CONFIG_PACKAGES_PATH
            vm_args_path = ONP_VM_ARGS_PACKAGES_PATH

        config_file_existed = config_file_initialized(app_config_path)
        if not config_file_existed:
            generate_config_file(app_config_path)

        set_node_name(vm_args_path)
        start_onepanel()

        update_persisted_version(previous_version=previous_version)

        batch_mode = os.environ.get('ONEPANEL_BATCH_MODE', 'false')
        if batch_mode.lower() == 'true':
            batch_config = get_batch_config()
            try:
                if configure(batch_config):
                    log('\nCongratulations! New Onezone deployment successfully started.')
                else:
                    log("\nWaiting for existing cluster to start...")
                    wait_for_workers()
                    log('Existing Onezone deployment resumed work.')
            except AuthenticationError as e:
                log('The launch script cannot access onepanel to manage the deployment process.\n'
                    'Please ensure that valid emergency passphrase is present\n'
                    'in the {} environment variable\n'
                    'or oversee the cluster status manually.'.format(EMERGENCY_PASSPHRASE_VARIABLE))
            except MissingVariableError as e:
                if e.variable_name != EMERGENCY_PASSPHRASE_VARIABLE:
                    raise
                if config_file_existed:
                    # most likely this is an existing deployment
                    log('Environment variable {} is missing.\n'
                        'An existing deployment will continue to work\n'
                        'but this script will not be able to track its startup.\n'
                        'You can fix this by setting the variable\n'
                        'to the Onepanel\' passphrase (formerly admin account\'s password).'
                        .format(EMERGENCY_PASSPHRASE_VARIABLE))
                else:
                    log('Environment variable {} is missing.\n'
                        'When deploying a new cluster this variable is required.\n'
                        'Please set it to your desired Onepanel emergency passphrase.\n'
                        .format(EMERGENCY_PASSPHRASE_VARIABLE))

        # show_details()  NOTE: currently not working correctly (all details are null)
    except Exception as e:
        log('\nERROR: {0}'.format(e))
        if os.environ.get('ONEPANEL_DEBUG_MODE', 'false').lower() == 'true':
            pass
        else:
            log(' ')
            log('Below is a dump of all application logs at the moment of failure:')
            log('-------------------------------------------------------------')
            print_logs(current_log_level, infinitely=False)
            log('-------------------------------------------------------------')
            log('ERROR: Starting the container failed - see above.')
            sys.exit(1)

    previous_log_cursors = print_logs(current_log_level, infinitely=False)
    with open(SERVICE_READY_LOCK_FILE, 'w'):
        pass
    print_logs(current_log_level, starting_log_cursors=previous_log_cursors, infinitely=True)
