#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import os
import re
import subprocess as sp
import sys
import textwrap
import time
import xml.etree.ElementTree as eTree
from dataclasses import dataclass
from enum import Enum, IntEnum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import requests
import yaml
from requests import codes
from requests.packages.urllib3.exceptions import InsecureRequestWarning

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)


# -----------------------------------------------------------------------------
# Components & logging
# -----------------------------------------------------------------------------

COMPONENTS = ["cluster_manager", "oz_panel", "oz_worker"]

LOGS = [
    ("[oz_panel]", "/var/log/oz_panel"),
    ("[cluster_manager]", "/var/log/cluster_manager"),
    ("[oz_worker]", "/var/log/oz_worker"),
]
LOG_LEVELS = ["debug", "info", "error"]


# -----------------------------------------------------------------------------
# Environment / authentication
# -----------------------------------------------------------------------------

# Username for Basic auth with the emergency passphrase
PASSPHRASE_USERNAME = "onepanel"
EMERGENCY_PASSPHRASE_VARIABLE = "ONEPANEL_EMERGENCY_PASSPHRASE"

WAIT_FOR_WORKER_RETRIES = 900


# -----------------------------------------------------------------------------
# Paths
# -----------------------------------------------------------------------------

# If onepanel is started from sources, contains the path to the root directory
# of the pre-built onepanel repo/artifact.
ONEPANEL_OVERRIDE = os.environ.get("ONEPANEL_OVERRIDE")

if ONEPANEL_OVERRIDE:
    LEGACY_VM_ARGS_PATH_TEMPLATE = os.path.join(
        ONEPANEL_OVERRIDE, "../{component}/_build/default/rel/{component}/etc/vm.args"
    )
    ONP_VM_ARGS_PATH = os.path.join(
        ONEPANEL_OVERRIDE, "_build/default/rel/oz_panel/etc/autogenerated.vm.args"
    )
    ONP_GENERATED_CONFIG_PATH = os.path.join(
        ONEPANEL_OVERRIDE, "_build/default/rel/oz_panel/etc/autogenerated.config"
    )
    ONP_RELEASES_PATH = os.path.join(
        ONEPANEL_OVERRIDE, "_build/default/rel/oz_panel/releases/RELEASES"
    )
else:
    LEGACY_VM_ARGS_PATH_TEMPLATE = "/etc/{component}/vm.args"
    ONP_VM_ARGS_PATH = "/etc/oz_panel/autogenerated.vm.args"
    ONP_GENERATED_CONFIG_PATH = "/etc/oz_panel/autogenerated.config"
    ONP_RELEASES_PATH = "/usr/lib/oz_panel/releases/RELEASES"

ONP_BIN_SOURCES_PATH = "_build/default/rel/oz_panel/bin/oz_panel"
ONP_VERSION_FILE_PACKAGES_PATH = "/etc/oz_panel/deployed-version.json"


# -----------------------------------------------------------------------------
# Templates & formatting
# -----------------------------------------------------------------------------

AUTOGENERATED_VM_ARGS_TEMPLATE = """# MACHINE GENERATED FILE. DO NOT MODIFY.

## Name of the node
-name {node}

## Cookie for distributed erlang
-setcookie {cookie}
"""

WRAP_KWARGS = {"width": 100, "break_long_words": False, "break_on_hyphens": False}


# -----------------------------------------------------------------------------
# Runtime / persistence
# -----------------------------------------------------------------------------

ONEPANEL_BASE_URL = "https://127.0.0.1:9443"

# Used by the "await" script to signal service readiness
SERVICE_READY_LOCK_FILE = "/root/service-ready.lock"

try:
    IS_CONFIG_INITIALIZED = bool(
        re.search(
            r"{config_initialized,\s*true}", Path(ONP_GENERATED_CONFIG_PATH).read_text()
        )
    )
except OSError:
    IS_CONFIG_INITIALIZED = False

ONP_DEFAULT_ASSUMED_VERSION = "20.02.1"  # when version file is missing


# -----------------------------------------------------------------------------
# User-facing messages
# -----------------------------------------------------------------------------

MSG_CONGRATULATIONS = "\nCongratulations! New Onezone deployment successfully started."
MSG_WAITING_FOR_CLUSTER = "\nWaiting for existing cluster to start..."
MSG_WAITING_FOR_PANEL = (
    "Waiting for oz_panel server to be available\n"
    "(may require starting other cluster nodes)\n"
)
MSG_RESUMED_WORK = "Existing Onezone deployment resumed work."
MSG_AUTHENTICATION_ERROR = (
    "The launch script cannot access onepanel to manage the deployment process.\n"
    "Please ensure that valid emergency passphrase is present\n"
    f"in the {EMERGENCY_PASSPHRASE_VARIABLE} environment variable\n"
    "or oversee the cluster status manually."
)
MSG_MISSING_EXISTING_PASSPHRASE = (
    f"Environment variable {EMERGENCY_PASSPHRASE_VARIABLE} is missing.\n"
    "An existing deployment will continue to work\n"
    "but this script will not be able to track its startup.\n"
    "You can fix this by setting the variable\n"
    "to the Onepanel' passphrase (formerly admin account's password)."
)
MSG_MISSING_NEW_PASSPHRASE = (
    f"Environment variable {EMERGENCY_PASSPHRASE_VARIABLE} is missing.\n"
    "When deploying a new cluster this variable is required.\n"
    "Please set it to your desired Onepanel emergency passphrase.\n"
)
MSG_FAILURE_DUMP_LOGS = (
    "\n"
    "Below is a dump of all application logs at the moment of failure:\n"
    "-------------------------------------------------------------\n"
)
MSG_FAILURE_FOOTER = (
    "-------------------------------------------------------------\n"
    "ERROR: Starting the container failed - see above."
)

MSG_COULD_NOT_RESOLVE_VERSION = """Could not resolve the previously deployed software version;
for versions < 25.1, this information is not supported. 
Assuming the previously running version was NOT LOWER THAN 20.02.1.

WARNING: if you are upgrading from version 19.02.* or lower, STOP the deployment
and first upgrade to 20.02.*. Otherwise, let it continue.

Sleeping for 30 seconds to let you react...
"""

SLEEP_COULD_NOT_RESOLVE_VERSION_SEC = 30

MSG_FRESH_DEPLOYMENT = """No previous persistence detected.

Starting a fresh deployment of Onezone in version {new_version} ...
"""

MSG_RESUME_SAME_VERSION = """Preexisting persistence has been detected, version {prev_version}

Resuming Onezone in version {current_version} ...
"""

MSG_RESUME_UPGRADE = """Preexisting persistence has been detected, version {prev_version}

Resuming Onezone and upgrading to version {current_version} ...

The upgrade will be performed during the startup of services. 
Please allow more time until the services are operational.

You may monitor the logs for details (paths inside the container):
/var/log/oz_panel/info.log
/var/log/oz_worker/info.log
"""

MSG_UPGRADE_JUMP_TOO_BIG = """Preexisting persistence has been detected, version {prev_version}

ERROR: You are attempting to run Onezone in version {current_version}

Upgrading by more than one major versions is not supported. Please upgrade to
an intermediate major version first, then start this version. Note that majors
21 and 25 are treated as the same one, due to reworked naming convention.

Exemplary allowed upgrades:
    21.02.8 -> 25.0
    21.02.2 -> 26.0
    25.0 -> 25.1
    25.1 -> 26.1
    20.02.6 -> 25.1

Exemplary disallowed upgrades:
    20.02.20 -> 26.0  (upgrade to 21.02.* / 25.* first)
"""

MSG_DOWNGRADE = """Preexisting persistence has been detected, version {prev_version}

ERROR: You are attempting to run Onezone in version {current_version}

Downgrades are not supported. Please use Onezone in version {prev_version} or newer.
"""


# -----------------------------------------------------------------------------
# Exceptions
# -----------------------------------------------------------------------------


class MissingVariableError(Exception):
    """Raised when a required environment variable is not set."""

    def __init__(self, variable_name: str) -> None:
        super().__init__(f"Missing {variable_name} environment variable")
        self.variable_name = variable_name


class AuthenticationError(Exception):
    """Raised when an API request is rejected due to invalid credentials."""


# -----------------------------------------------------------------------------
# Data types
# -----------------------------------------------------------------------------


class Label(IntEnum):
    """Label specifiers for pre-releases.

    Ordered by precedence: alpha < beta < rc < stable (no label).
    """

    ALPHA = 1
    BETA = 2
    RC = 3
    STABLE = 4

    @classmethod
    def from_string(cls, s: str) -> "Label":
        if s == "alpha":
            return cls.ALPHA
        if s == "beta":
            return cls.BETA
        if s == "rc":
            return cls.RC
        raise ValueError(f"Unknown label: {s}")


@dataclass(frozen=True, order=True)
class Revision:
    """Represents a system revision based on Calendar Versioning.

    Format: YY.Minor[.Patch][-Label]

    Examples:
        25.0-alpha.1
        25.0
        25.0.1
    """

    year: int
    minor: int
    patch: int = 0
    label: Label = Label.STABLE
    label_ordinal: int = 0


class UpgradabilityCheckResult(Enum):
    """Result of comparing previous and new version for startup."""

    SAME_VERSION = 1
    ALLOWED_UPGRADE = 2
    UPGRADE_JUMP_TOO_BIG = 3
    DOWNGRADE = 4


# =============================================================================
# Main entry point
# =============================================================================


def main() -> None:
    current_log_level = os.environ.get("ONEPANEL_LOG_LEVEL", "info").lower()
    try:
        previous_version = assert_upgradability()

        preconfigure()
        start_onepanel_and_await_readiness()

        update_persisted_version(previous_version=previous_version)

        if env_bool("ONEPANEL_BATCH_MODE"):
            configure_deployment()

        # show_details()  NOTE: currently not working correctly (all details are null)
    except Exception as e:
        log(f"\nERROR: {e}")
        if env_bool("ONEPANEL_DEBUG_MODE"):
            # Keep container running for inspection; do not dump logs or exit
            pass
        else:
            log(MSG_FAILURE_DUMP_LOGS)
            print_logs(current_log_level, infinitely=False)
            log(MSG_FAILURE_FOOTER)
            sys.exit(1)

    previous_log_cursors = print_logs(current_log_level, infinitely=False)
    with open(SERVICE_READY_LOCK_FILE, "w"):
        pass
    print_logs(
        current_log_level, starting_log_cursors=previous_log_cursors, infinitely=True
    )


# =============================================================================
# Upgradability checks
# =============================================================================


def assert_upgradability() -> Optional[str]:
    """Check upgradability based on versions.

    Returns previous_version for persistence when not fresh install, None otherwise.
    Exits on disallowed upgrade or downgrade.
    """
    new_version = infer_new_version()

    if not IS_CONFIG_INITIALIZED:
        log(MSG_FRESH_DEPLOYMENT.format(new_version=new_version))
        return None

    prev_version = infer_previous_version()
    result = check_upgradability(prev_version, new_version)

    if result == UpgradabilityCheckResult.DOWNGRADE:
        log(
            MSG_DOWNGRADE.format(prev_version=prev_version, current_version=new_version)
        )
        sys.exit(1)

    elif result == UpgradabilityCheckResult.UPGRADE_JUMP_TOO_BIG:
        log(
            MSG_UPGRADE_JUMP_TOO_BIG.format(
                prev_version=prev_version,
                current_version=new_version,
            )
        )
        sys.exit(1)

    elif result == UpgradabilityCheckResult.SAME_VERSION:
        log(
            MSG_RESUME_SAME_VERSION.format(
                prev_version=prev_version,
                current_version=new_version,
            )
        )

    elif result == UpgradabilityCheckResult.ALLOWED_UPGRADE:
        log(
            MSG_RESUME_UPGRADE.format(
                prev_version=prev_version,
                current_version=new_version,
            )
        )

    return prev_version


def infer_new_version() -> str:
    """Parse RELEASES file and return the onepanel version string (e.g. "25.0").

    Exits with a message if file is missing or version pattern not found.
    """
    if not os.path.isfile(ONP_RELEASES_PATH):
        log(f"Could not find RELEASES file at {ONP_RELEASES_PATH}")
        sys.exit(1)

    try:
        with open(ONP_RELEASES_PATH, "r") as f:
            content = f.read()
        # e.g. {onepanel,"25.0","./lib/onepanel-25.0"}
        m = re.search(r'\{onepanel\s*,\s*["\']([^"\']+)["\']', content)
        if m:
            return m.group(1).strip()
    except OSError as e:
        log(f"Failed to read RELEASES file {ONP_RELEASES_PATH}: {e}")
        sys.exit(1)

    log(f"Could not find onepanel version in RELEASES file: {ONP_RELEASES_PATH}")
    sys.exit(1)


def infer_previous_version():
    try:
        with open(ONP_VERSION_FILE_PACKAGES_PATH, "r") as f:
            data = json.load(f)

        return data["current"]
    except (OSError, ValueError):
        log(MSG_COULD_NOT_RESOLVE_VERSION)
        time.sleep(SLEEP_COULD_NOT_RESOLVE_VERSION_SEC)

        return ONP_DEFAULT_ASSUMED_VERSION


def check_upgradability(
    prev_version_str: str, new_version_str: str
) -> UpgradabilityCheckResult:
    prev_rev = parse_revision(prev_version_str.strip())
    new_rev = parse_revision(new_version_str.strip())

    if new_rev < prev_rev:
        return UpgradabilityCheckResult.DOWNGRADE
    elif new_rev > prev_rev:
        if (new_rev.year - prev_rev.year) <= 1:
            return UpgradabilityCheckResult.ALLOWED_UPGRADE
        elif new_rev.year == 25 and prev_rev.year in (20, 21):
            return UpgradabilityCheckResult.ALLOWED_UPGRADE
        elif new_rev.year == 26 and prev_rev.year in (21, 25):
            return UpgradabilityCheckResult.ALLOWED_UPGRADE

        return UpgradabilityCheckResult.UPGRADE_JUMP_TOO_BIG

    return UpgradabilityCheckResult.SAME_VERSION


def parse_revision(version_str: str) -> Revision:
    try:
        if not version_str:
            raise ValueError("Empty revision string")

        # Split main part and label
        parts = version_str.split("-", 1)
        main_part = parts[0]
        label_part = parts[1] if len(parts) > 1 else None

        # Parse numbers
        numbers = [int(n) for n in main_part.split(".")]
        if len(numbers) == 2:
            year, minor = numbers
            patch = 0
        elif len(numbers) == 3:
            year, minor, patch = numbers
        else:
            raise ValueError("Invalid version number format")

        # Parse label
        if label_part is None:
            label = Label.STABLE
            ordinal = 0
        else:
            if year > 21:
                # Modern format: label.ordinal (e.g., alpha.2)
                if "." not in label_part:
                    raise ValueError("Invalid modern label format")
                lbl_str, ord_str = label_part.split(".", 1)
                label = Label.from_string(lbl_str)
                ordinal = int(ord_str)
            else:
                # Legacy format: labelordinal (e.g., alpha2)
                match = re.match(r"([a-z]+)(\d+)", label_part)
                if not match:
                    raise ValueError("Invalid legacy label format")
                lbl_str, ord_str = match.groups()
                label = Label.from_string(lbl_str)
                ordinal = int(ord_str)

        return Revision(
            year=year, minor=minor, patch=patch, label=label, label_ordinal=ordinal
        )
    except Exception as e:
        raise ValueError(f"Invalid revision format '{version_str}': {e}") from e


def update_persisted_version(previous_version: Optional[str] = None) -> None:
    """Write deployed-version.json.

    When previous_version is None (fresh deploy),only current is written.
    Otherwise, both previous and current are stored.
    """
    current = infer_new_version()
    data: Dict[str, str] = {"current": current}
    if previous_version is not None:
        data["previous"] = previous_version

    os.makedirs(os.path.dirname(ONP_VERSION_FILE_PACKAGES_PATH), exist_ok=True)
    with open(ONP_VERSION_FILE_PACKAGES_PATH, "w") as f:
        json.dump(data, f, indent=4)


# =============================================================================
# Configuration (app.config, vm.args)
# =============================================================================


def preconfigure() -> None:
    """Prepare app.config and vm.args."""
    upgrade_legacy_vm_args_if_exists()

    if not IS_CONFIG_INITIALIZED:
        generate_config_file(ONP_GENERATED_CONFIG_PATH)

    set_node_name(ONP_VM_ARGS_PATH)


def upgrade_legacy_vm_args_if_exists() -> None:
    """Migrate old-style vm.args files to the autogenerated format."""
    for component in COMPONENTS:
        legacy_vm_args_path = LEGACY_VM_ARGS_PATH_TEMPLATE.format(component=component)

        if os.path.exists(legacy_vm_args_path):
            upgrade_legacy_vm_args(legacy_vm_args_path)


def upgrade_legacy_vm_args(legacy_vm_args_path: str) -> None:
    with open(legacy_vm_args_path, "r") as f:
        content = f.read()

    node = re.search(r"-name (?P<node>.*)", content).group("node")
    cookie = re.search(r"-setcookie (?P<cookie>.*)", content).group("cookie")

    autogenerated_vm_args_path = os.path.join(
        os.path.dirname(legacy_vm_args_path), "autogenerated.vm.args"
    )

    with open(autogenerated_vm_args_path, "w") as f:
        f.write(AUTOGENERATED_VM_ARGS_TEMPLATE.format(node=node, cookie=cookie))

    os.remove(legacy_vm_args_path)

    log(
        f"Upgraded legacy vm.args: {legacy_vm_args_path} -> {autogenerated_vm_args_path}"
    )


def generate_config_file(file_path: str) -> None:
    """Build the initial onepanel autogenerated.config with env-driven options."""

    content = (
        "% MACHINE GENERATED FILE. DO NOT MODIFY.\n"
        "% Use overlay.config for custom configuration.\n\n"
        "[{onepanel, [{config_initialized, true}"
    )

    if os.environ.get("ONEPANEL_GENERATE_TEST_WEB_CERT"):
        domain = os.environ.get("ONEPANEL_GENERATED_CERT_DOMAIN", "")
        flag = str(env_bool("ONEPANEL_GENERATE_TEST_WEB_CERT")).lower()
        content += f",\n{{generate_test_web_cert, {flag}}}"
        content += f',\n{{test_web_cert_domain, "{domain}"}}'

    if os.environ.get("ONEPANEL_TRUST_TEST_CA"):
        flag = str(env_bool("ONEPANEL_TRUST_TEST_CA")).lower()
        content += f",\n{{treat_test_ca_as_trusted, {flag}}}"

    content += "\n]}]."

    with open(file_path, "w") as f:
        f.write(content)


def set_node_name(file_path: str) -> None:
    hostname = sp.check_output(["hostname", "-f"]).decode().rstrip("\n")
    replace_in_file(file_path, r"-name .*", f"-name onepanel@{hostname}")


# =============================================================================
# Onepanel service lifecycle
# =============================================================================


def start_onepanel_and_await_readiness() -> None:
    log("Starting oz_panel...")

    cmd = ["service", "oz_panel", "start"]
    if ONEPANEL_OVERRIDE:
        oz_panel_script = os.path.join(ONEPANEL_OVERRIDE, ONP_BIN_SOURCES_PATH)
        cmd = [oz_panel_script, "start"]

    try:
        sp.check_output(cmd)
    except sp.CalledProcessError as err:
        log(f"ERROR: {err}")
        log("Output was:\n")
        log(str(err.output))
        sys.exit(err.returncode)

    wait_for_rest_listener()
    log("[  OK  ] oz_panel started\n")


def wait_for_rest_listener() -> None:
    first = True
    connected = False
    while not connected:
        try:
            requests.get(f"{ONEPANEL_BASE_URL}/api/v3/onepanel/", verify=False)
        except requests.ConnectionError:
            if first:
                log(MSG_WAITING_FOR_PANEL)
                first = False
            time.sleep(1)
        else:
            connected = True


def configure_deployment() -> None:
    batch_config = get_batch_config()
    try:
        if configure(batch_config):
            log(MSG_CONGRATULATIONS)
        else:
            log(MSG_WAITING_FOR_CLUSTER)
            wait_for_workers()
            log(MSG_RESUMED_WORK)
    except AuthenticationError:
        log(MSG_AUTHENTICATION_ERROR)
    except MissingVariableError as e:
        if e.variable_name != EMERGENCY_PASSPHRASE_VARIABLE:
            raise

        if IS_CONFIG_INITIALIZED:
            log(MSG_MISSING_EXISTING_PASSPHRASE)
        else:
            log(MSG_MISSING_NEW_PASSPHRASE)


def get_batch_config():
    batch_config = os.environ.get("ONEZONE_CONFIG", "")
    batch_config = yaml.safe_load(batch_config)
    if not batch_config:
        return {}

    # insert interactiveDeployment mark if not present
    onepanel_config = batch_config.get("onepanel", {})
    if "interactiveDeployment" not in onepanel_config:
        onepanel_config["interactiveDeployment"] = False
        batch_config["onepanel"] = onepanel_config

    return batch_config


def configure(config: dict) -> bool:
    """Attempts to deploy the Onezone.

    Returns False if configuration was skipped because of existing deployment,
    True upon success.
    """
    passphrase = get_emergency_passphrase()

    try:
        set_emergency_passphrase(passphrase)
    except AuthenticationError:
        # emergency passphrase setup failure indicates existing deployment
        return False

    r = auth_request(
        requests.post,
        f"{ONEPANEL_BASE_URL}/api/v3/onepanel/zone/configuration",
        headers={"content-type": "application/x-yaml"},
        data=yaml.dump(config),
        verify=False,
    )

    if r.status_code == codes.conflict:
        return False

    if not r.ok:
        raise RuntimeError(
            f"Failed to start configuration process, the response was:\n"
            f"  code: {r.status_code}\n"
            f"  body: {r.text}\n"
            f"For more information please check the logs."
        )

    poll_configuration_status(r.headers["location"])
    return True


def poll_configuration_status(location: str) -> None:
    """Poll the onepanel task endpoint until configuration completes or fails."""
    status = "running"
    steps: List[str] = []
    resp: dict = {}

    log("\nConfiguring Onezone:")
    while status == "running":
        r = auth_request(requests.get, ONEPANEL_BASE_URL + location, verify=False)
        if not r.ok:
            raise RuntimeError(
                f"Unexpected configuration error\n{r.text}"
                f"For more information please check the logs."
            )

        resp = json.loads(r.text)
        status = resp.get("status", "error")
        for step in resp.get("steps", []):
            if steps and step == steps[0]:
                steps = steps[1:]
            else:
                log(format_step(step))
        steps = resp.get("steps", [])
        time.sleep(1)

    if status != "ok":
        raise RuntimeError(format_error(resp))


def get_emergency_passphrase() -> str:
    passphrase = os.environ.get(EMERGENCY_PASSPHRASE_VARIABLE)
    if passphrase is None:
        raise MissingVariableError(EMERGENCY_PASSPHRASE_VARIABLE)
    return passphrase


def set_emergency_passphrase(passphrase: str) -> None:
    r = requests.put(
        f"{ONEPANEL_BASE_URL}/api/v3/onepanel/emergency_passphrase",
        headers={"content-type": "application/json"},
        data=json.dumps({"newPassphrase": passphrase}),
        verify=False,
    )
    if r.status_code in (codes.unauthorized, codes.forbidden):
        raise AuthenticationError(
            "Could not set Onepanel emergency passphrase due to "
            f"authentication error: {r.status_code} {r.text}"
        )
    if not r.ok:
        raise RuntimeError(
            f"Could not set Onepanel emergency passphrase: {r.status_code} {r.text}"
        )


def auth_request(method: Any, *args: Any, **kwargs: Any) -> requests.Response:
    """Perform an HTTP request with Basic auth using the emergency passphrase."""
    passphrase = get_emergency_passphrase()
    r = method(*args, auth=(PASSPHRASE_USERNAME, passphrase), **kwargs)
    if r.status_code in (codes.unauthorized, codes.forbidden):
        raise AuthenticationError(
            "Authentication error.\n"
            "Please ensure that valid emergency passphrase is present\n"
            f"in the {EMERGENCY_PASSPHRASE_VARIABLE} environment variable"
        )
    return r


# =============================================================================
# Health monitoring & log tailing
# =============================================================================


def wait_for_workers() -> None:
    url = f"{ONEPANEL_BASE_URL}/api/v3/onepanel/zone/nagios"
    retries = 0
    while not is_nagios_healthy(url, retries % 30 == 10):  # first log after 10 seconds
        time.sleep(1)
        retries += 1
        if retries == WAIT_FOR_WORKER_RETRIES:
            raise RuntimeError("Timeout waiting for the Onepanel service readiness")


def is_nagios_healthy(url: str, log_errors: bool = False) -> bool:
    try:
        r = auth_request(requests.get, url, verify=False)
        if not r.ok:
            if log_errors:
                log(
                    "Onepanel service is reachable, but nagios is not reporting an OK status - retrying...\n"
                    "This could mean that services take longer to start due to e.g. Couchbase DB reorganization.\n"
                    "Allow some time (usually about 5 minutes, but sometimes much longer) and do not interrupt the process.\n"
                    "You may consult the logs for more details:\n"
                    "  - /var/log/oz_worker/info.log\n"
                    "  - /var/log/oz_panel/info.log\n"
                    "  - /opt/couchbase/var/lib/couchbase/logs/info.log\n"
                )
            return False
    except Exception:
        if log_errors:
            log("Onepanel service is not reachable - retrying...")
        return False

    healthdata = eTree.fromstring(r.text)
    return healthdata.attrib["status"] == "ok"


# =============================================================================
# Display & formatting
# =============================================================================


def show_details() -> None:
    log("\nContainer details:")

    container_id = get_container_id()
    container_info = inspect_container(container_id)

    show_ip_address(container_info)
    show_ports(container_info)


def get_container_id() -> str:
    with open("/proc/self/cgroup", "r") as f:
        return f.readline().split("/")[-1].rstrip("\n")


def inspect_container(container_id: str) -> dict:
    try:
        result = sp.check_output(
            [
                "curl",
                "-s",
                "--unix-socket",
                "/var/run/docker.sock",
                f"http:/containers/{container_id}/json",
            ]
        )
        return json.loads(result)
    except Exception:
        return {}


def show_ip_address(container_info: dict) -> None:
    ip = "-"
    try:
        ip = list(container_info["NetworkSettings"]["Networks"].items())[0][1][
            "IPAddress"
        ]
    except (KeyError, IndexError, TypeError):
        try:
            ip = sp.check_output(["hostname", "-i"]).decode().rstrip("\n")
        except Exception:
            pass
    log(f"* IP Address: {ip}")


def show_ports(container_info: dict) -> None:
    ports = container_info.get("NetworkSettings", {}).get("Ports", {})
    ports_format = []
    for container_port in ports:
        host = ports[container_port]
        if host:
            for host_port in host:
                ports_format.append(
                    f"{host_port['HostIp']}:{host_port['HostPort']} -> {container_port}"
                )
        else:
            ports_format.append(container_port)
    ports_str = "\n         ".join(ports_format) if ports_format else "-"
    log(f"* Ports: {ports_str}")


def format_step(step: str) -> str:
    service, action = step.split(":")
    return f"* {service}: {action}"


def format_error(response: dict) -> str:
    if "error" not in response:
        return "Error: unexpected server response"
    error_obj = response["error"]
    error_id, descr, details, nodes = unwrap_error_with_hosts(error_obj)
    details_str = format_dict(details, "    ")

    if details_str:
        details_str = "  details:\n" + details_str
    nodes_str = ""
    if nodes:
        nodes_str = "  nodes:\n    " + "\n    ".join(sorted(nodes))
    descr_str = textwrap.fill(
        "description: " + descr,
        initial_indent="  ",
        subsequent_indent="    ",
        **WRAP_KWARGS,
    )
    return f"Error:\n  id: {error_id}\n{nodes_str}\n{descr_str}\n{details_str}"


def format_dict(details: dict, indent: str) -> str:
    result = ""
    for key, value in list(details.items()):
        if isinstance(value, dict):
            result += f"{indent}{key}:\n"
            result += format_dict(value, indent + "  ")
        else:
            result += (
                textwrap.fill(
                    f"{key}: {value}",
                    initial_indent=indent,
                    subsequent_indent=indent + "  ",
                    **WRAP_KWARGS,
                )
                + "\n"
            )
    return result


def unwrap_error_with_hosts(error_obj: dict) -> Tuple[str, str, dict, List[str]]:
    """Extracts original error from a wrapper listing hosts
    where the error occurred."""
    error_id = error_obj.get("id")
    description = error_obj.get("description")
    details = error_obj.get("details", {})
    nodes: List[str] = []

    if error_id == "errorOnNodes" and "error" in details:
        error_id = details["error"]["id"]
        description = details["error"]["description"]
        nodes = details["hostnames"]
        details = details["error"].get("details", {})

    return error_id, description, details, nodes


def print_logs(log_level, starting_log_cursors=None, infinitely=True):
    # first run of the function
    if not isinstance(starting_log_cursors, list):
        starting_log_cursors = []
        if log_level in LOG_LEVELS:
            log("\nLogging on '{0}' level:".format(log_level))
            for log_prefix, log_dir in LOGS:
                log_file = os.path.join(log_dir, log_level + ".log")
                starting_log_cursors.append((log_prefix, log_file, None, None))
        else:
            log("\nLogging to stdout disabled (log level = {})".format(log_level))

    new_log_cursors = print_new_logs(starting_log_cursors)
    while infinitely:
        new_log_cursors = print_new_logs(new_log_cursors)
        time.sleep(1)
    return new_log_cursors


def print_new_logs(log_cursors):
    new_logs = []

    for log_prefix, log_file, log_fd, log_ino in log_cursors:
        try:
            if os.stat(log_file).st_ino != log_ino:
                if log_fd:
                    log_fd.close()
                log_fd = open(log_file, "r")
                log_ino = os.stat(log_file).st_ino

            log_line = log_fd.readline()
            while log_line:
                log("{0} {1}".format(log_prefix, log_line), end="")
                log_line = log_fd.readline()

            new_logs.append((log_prefix, log_file, log_fd, log_ino))
        except:
            new_logs.append((log_prefix, log_file, None, None))

    return new_logs


# =============================================================================
# Utilities
# =============================================================================


def log(message: str, end: str = "\n") -> None:
    sys.stdout.write(message + end)
    sys.stdout.flush()


def replace_in_file(file_path: str, pattern: str, value: str) -> None:
    with open(file_path, "r+") as f:
        content = f.read()
        content = re.sub(pattern, value, content)
        f.seek(0)
        f.truncate()
        f.write(content)


def env_bool(key: str, default: bool = False) -> bool:
    """Interpret an environment variable as a boolean (truthy: 'true', '1')."""
    return os.environ.get(key, str(default)).lower() in ("true", "1")


if __name__ == "__main__":
    main()
