import json
import requests
import sys
import time
from requests.packages.urllib3.exceptions import InsecureRequestWarning
from subprocess import STDOUT, check_call, check_output

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

dist = sys.argv[1].encode()

EMERGENCY_USERNAME = 'onepanel'
EMERGENCY_PASSPHRASE = 'passphrase'

# get packages
packages = check_output(['ls', '/root/pkg']).split()
packages = sorted(packages, reverse=True)
oz_panel_package = \
    [path for path in packages if path.decode().startswith('oz-panel')
                                  and (dist in path)][0].decode()
cluster_manager_package = \
    [path for path in packages if path.decode().startswith('cluster-manager')
                                  and (dist in path)][0].decode()
oz_worker_package = \
    [path for path in packages if path.decode().startswith('oz-worker')
                                  and (dist in path)][0].decode()
onezone_package = [path for path in packages if path.decode().startswith('onezone')
                                                and (dist in path)][0].decode()

# get couchbase
check_call(['wget', 'http://packages.onedata.org/apt/ubuntu/xenial/pool/' \
                    'main/c/couchbase-server-community/couchbase-' \
                    'server-community_4.5.1-ubuntu14.04_amd64.deb'])

check_call(['wget', 'http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0'
                        '/libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb'])

# install packages
check_call(['sh', '-c', 'apt install -f -y '
                './libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb'
                            ], stderr=STDOUT)
check_call(['sh', '-c',
            'dpkg -i couchbase-server-community_4.5.1-ubuntu14.04_amd64.deb '
            '; apt-get -f -y install'], stderr=STDOUT)
check_call(['sh', '-c', 'DEBIAN_FRONTEND=noninteractive apt install -y '
            'python2 python-is-python2'], stderr=STDOUT)
check_call(['sh', '-c', 'DEBIAN_FRONTEND=noninteractive apt install -y /root/pkg/{package}'
                        .format(package=oz_panel_package)], stderr=STDOUT)
check_call(['sh', '-c', 'DEBIAN_FRONTEND=noninteractive apt install -y /root/pkg/{package}'
                .format(package=cluster_manager_package)], stderr=STDOUT)
check_call(['sh', '-c', 'DEBIAN_FRONTEND=noninteractive apt install -y /root/pkg/{package}'
                        .format(package=oz_worker_package)], stderr=STDOUT)
check_call(['sh', '-c', 'DEBIAN_FRONTEND=noninteractive apt install -y /root/pkg/{package}'
                        .format(package=onezone_package)], stderr=STDOUT)

# validate packages installation
check_call(['service', 'oz_panel', 'status'])
check_call(['ls', '/etc/cluster_manager/autogenerated.config'])
check_call(['ls', '/etc/oz_worker/autogenerated.config'])

# configure onezone
with open('/root/data/config.yml', 'r') as f:
    r = requests.put('https://127.0.0.1:9443/api/v3/onepanel/emergency_passphrase',
        headers={'content-type': 'application/json'},
        data=json.dumps({'newPassphrase': EMERGENCY_PASSPHRASE}),
        verify=False)
    assert r.status_code == 204

    r = requests.post(
        'https://127.0.0.1:9443/api/v3/onepanel/zone/configuration',
        auth=(EMERGENCY_USERNAME, EMERGENCY_PASSPHRASE),
        headers={'content-type': 'application/x-yaml'},
        data=f.read(),
        verify=False)

    loc = r.headers['location']
    status = 'running'
    while status == 'running':
        r = requests.get('https://127.0.0.1:9443' + loc,
                         auth=(EMERGENCY_USERNAME, EMERGENCY_PASSPHRASE),
                         verify=False)
        print(r.text)
        assert r.status_code == 200
        status = json.loads(r.text)['status']
        time.sleep(5)

assert status == 'ok'

# validate oneprovider configuration
check_call(['service', 'cluster_manager', 'status'])
check_call(['service', 'oz_worker', 'status'])

# stop onezone services
for service in ['workers', 'managers', 'databases']:
    r = requests.patch(
        'https://127.0.0.1:9443/api/v3/onepanel/zone/{0}?started=false'.format(
            service),
        auth=(EMERGENCY_USERNAME, EMERGENCY_PASSPHRASE),
        headers={'content-type': 'application/json'},
        verify=False)
    assert r.status_code == 204

sys.exit(0)
